import { applyCatalogPriceOffset } from "./catalogPrice";
import { resolveProductColors } from "./productColors";
import { withPublicAssetVersion } from "./publicAsset";

const CATALOG_DISCOUNT = 40;

export const rawProductsData = [
  // Summer Essentials pieces
  // Prices are stored before the catalog offset so the storefront displays the requested offer values.
  {
    _id: "p-summer-jacket-001",
    name: "Premium Summer Jacket",
    category: "jackets-coats",
    price: 1200,
    images: ["/uploads/image4.png", "/uploads/image1.png"],
    size: ["M", "L", "XL", "2XL"],
    description:
      "A lightweight textured summer jacket with a dark bronze wash, sharp collar, and relaxed luxury fit.",
    material: "Premium washed cotton blend.",
    colors: ["black", "bronze"],
    stock: 12,
  },
  {
    _id: "p-summer-pants-001",
    name: "Premium Tailored Pants",
    category: "korean",
    price: 1200,
    images: ["/uploads/image3.png", "/uploads/image1.png"],
    size: ["M", "L", "XL", "2XL"],
    description:
      "Cream tailored summer pants with clean drape, soft structure, and an easy elevated fit.",
    material: "Soft stretch cotton twill.",
    colors: ["cream", "ivory"],
    stock: 14,
  },
  {
    _id: "p-summer-sneakers-001",
    name: "Premium Summer Sneakers",
    category: "lace-ups",
    price: 1200,
    images: ["/uploads/image2.png", "/uploads/image1.png"],
    size: ["40", "41", "42", "43", "44"],
    description:
      "Polished black lace-up shoes with a clean round toe and modern lug sole for day-to-night summer styling.",
    material: "Smooth leather finish with a structured rubber sole.",
    colors: ["black"],
    stock: 10,
  },
  {
    _id: "p-summer-tshirt-001",
    name: "Essential Basic T-Shirt",
    category: "shirts",
    price: 200,
    images: ["/uploads/d76ef0f9-2b5c-4fc1-8aed-a80392d4c131.jpeg", "/uploads/image1.png"],
    size: ["M", "L", "XL", "2XL"],
    description:
      "A clean black basic T-shirt cut for layering under summer jackets or wearing alone with tailored pants.",
    material: "Soft premium cotton jersey.",
    colors: ["black"],
    stock: 18,
  },

  // Jackets & Coats
 
  {
    _id: "p-jc-003",
    name: "Wool-Blend Trench Coat",
    category: "jackets-coats",
    price: 1500,
    images: ["/uploads/whitejacket.jpg", "/uploads/peig_leather_jacket.jpg"],
    size: ["M", "L", "XL"],
    description: "A modern trench with a tailored shoulder.",
    colors: ["cream"],
  },
  
  {
    _id: "p-jc-007",
    name: "Navy Embroidered Bomber",
    category: "jackets-coats",
    price: 1000,
    images: [
      "/uploads/italian_jacket3.jpg",
      "/uploads/italian_jacket.jpg",
      "/uploads/italian_jacket2.jpg",
    ],
    size: ["M", "L", "XL"],
    description: "Navy Embroidered Bomber",
    colors: ["camel", "navy"],
  },
 
  {
    _id: "p-jc-011",
    name: "Urban Brown Leather Jacket",
    category: "jackets-coats",
    price: 1500,
    images: ["/uploads/brownleather2.jpg", "/uploads/brown_wind_jacket.jpg"],
    size: ["M", "L", "XL"],
    description: "Urban Brown Leather Jacket",
    colors: ["brown"],
  },
  {
    _id: "p-jc-012",
    name: "Dark Urban Bomber Jacket",
    category: "jackets-coats",
    price: 1500,
    images: ["/uploads/black.jpg", "/uploads/black_wind_jacket.jpg"],
    size: ["M", "L", "XL"],
    description: "Dark Urban Bomber Jacket",
    colors: ["black"],
  },
  {
    _id: "p-jc-014",
    name: "gray Urban Bomber Jacket",
    category: "jackets-coats",
    price: 1500,
    images: ["/uploads/greyjacket.jpg", "/uploads/greyjacket2.jpg"],
    size: ["M", "L", "XL"],
    description: "gray Urban Bomber Jacket",
    colors: ["gray"],
  },
  {
    _id: "p-jc-016",
    name: "Cream Geometric Quilted Shacket",
    category: "jackets-coats",
    price: 1470,
    discount: 40,
    images: ["/uploads/Cream Geometric Quilted Shacket.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Cream quilted shacket with a geometric matelasse pattern.",
    colors: ["cream", "gray"],
  },
  {
    _id: "p-jc-017",
    name: "Cream Zip-Up Harrington Jacket",
    category: "jackets-coats",
    price: 1470,
    images: ["/uploads/Cream Zip-Up Harrington Jacket.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Minimal cream harrington jacket with a clean zip-front profile.",
    colors: ["cream"],
  },
  {
    _id: "p-jc-018",
    name: "Textured Waffle-Knit Zip Jacket",
    category: "jackets-coats",
    price: 1200,
    images: ["/uploads/Textured Waffle-Knit Zip Jacket.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Lightweight zip jacket in a cream waffle-knit texture.",
    colors: ["cream"],
  },

  // Suits
  {
    _id: "p-su-001",
    name: "Minimal Cream Street Set",
    category: "suits",
    price: 2149,
    images: ["/uploads/whitesuit.jpg", "/uploads/peig_suit2.jpg"],
    size: ["38", "40", "42", "44"],
    description: "Minimal Cream Street Set",
    colors: ["cream"],
  },
  {
    _id: "p-su-003",
    name: "Mocha Casual Street Set",
    category: "suits",
    price: 2149,
    images: ["/uploads/brownsuit.jpg", "/uploads/brown_suit.jpg"],
    size: ["38", "40", "42"],
    description: "Mocha Casual Street Set",
    colors: ["mocha"],
  },

  // Shirts
  {
    _id: "p-sh-003",
    name: "Black & White Striped Polo Sweater",
    category: "shirts",
    price: 1080,
    images: ["/uploads/Black & White Striped Polo Sweater.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Striped rib-knit polo sweater in black and white.",
    colors: ["black", "white"],
  },
  {
    _id: "p-sh-004",
    name: "Cream Polo Collar Sweatshirt",
    category: "shirts",
    price: 1470,
    images: ["/uploads/Cream Polo Collar Sweatshirt.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Relaxed cream sweatshirt finished with a polo collar.",
    colors: ["cream"],
  },
  {
    _id: "p-sh-005",
    name: "Poker Face Tan Ribbed Polo",
    category: "shirts",
    price: 680,
    images: ["/uploads/Poker Face Tan Ribbed Polo.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Tan ribbed polo with a clean open-collar neckline.",
    colors: ["tan"],
  },
  {
    _id: "p-sh-006",
    name: "Cafe Ribbed Zip Polo",
    category: "shirts",
    price: 699,
    images: [
      "/uploads/beige-ribbed-zip-polo-product.png",
      "/uploads/beige-ribbed-zip-polo-editorial.png",
    ],
    size: ["M", "L", "XL", "2XL"],
    description:
      "Beige ribbed short-sleeve zip polo with a refined cafe-inspired summer fit.",
    material: "Soft rib-knit cotton blend.",
    colors: ["beige", "tan"],
    stock: 16,
  },

  // Knitwear
  {
    _id: "p-kn-001",
    name: "Dark Charcoal Chenille Turtleneck",
    category: "knitwear",
    price: 870,
    images: ["/uploads/Dark Charcoal Chenille Turtleneck.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Soft chenille turtleneck in a dark charcoal tone.",
    colors: ["charcoal"],
  },
  {
    _id: "p-kn-002",
    name: "Balenciaga Gradient Logo Sweater",
    category: "knitwear",
    price: 1200,
    images: ["/uploads/Balenciaga Gradient Logo Sweater.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Brown-to-camel gradient sweater with tonal Balenciaga branding.",
    colors: ["brown", "camel"],
  },
  {
    _id: "p-kn-003",
    name: "Beige Essential Rib-Knit Sweater",
    category: "knitwear",
    price: 870,
    images: ["/uploads/Beige Essential Rib-Knit Sweater.jpg"],
    size: ["M"],
    description: "Beige rib-knit sweater with contrast tipped trim.",
    colors: ["beige", "white"],
  },
  {
    _id: "p-kn-004",
    name: "Charcoal Quarter-Zip Pullover",
    category: "knitwear",
    price: 870,
    images: ["/uploads/Charcoal Quarter-Zip Pullover.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Charcoal pullover with a clean quarter-zip neckline.",
    colors: ["charcoal"],
  },
  {
    _id: "p-kn-005",
    name: "Essential Turtleneck Sweater (Ivory)",
    category: "knitwear",
    price: 680,
    images: ["/uploads/Essential Turtleneck Sweater (Ivory).jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Essential ivory turtleneck sweater with a clean minimalist finish.",
    colors: ["cream"],
  },
  {
    _id: "p-kn-006",
    name: "Tommy Hilfiger Striped Hoodie (Tan:Brown)",
    category: "knitwear",
    price: 870,
    images: ["/uploads/Tommy Hilfiger Striped Hoodie (Tan:Brown).jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Striped knit hoodie in tan, brown, and white.",
    colors: ["tan", "brown", "white"],
  },

  // Bags & Wallets
  // { _id: "p-bw-001", name: "Pebbled Leather Tote", category: "bags-wallets", price: 399, images: ["/uploads/Bags & Wallets.jpg"], size: [], description: "Structured tote with pebbled leather texture.", colors: ["black"] },
  // { _id: "p-bw-002", name: "Compact Card Holder", category: "bags-wallets", price: 69, images: ["/uploads/Bags & Wallets.jpg"], size: [], description: "Slim profile with four card slots.", colors: ["black", "brown"] },
  // { _id: "p-bw-003", name: "Zip-Around Wallet", category: "bags-wallets", price: 129, images: ["/uploads/Bags & Wallets.jpg"], size: [], description: "Secure zip-around wallet with interior organization.", colors: ["navy", "black"] },
  // { _id: "p-bw-004", name: "Mini Crossbody Bag", category: "bags-wallets", price: 219, images: ["/uploads/Bags & Wallets.jpg"], size: [], description: "Minimal crossbody for essentials only.", colors: ["black", "tan"] },

  // Belts
  // { _id: "p-be-001", name: "Reversible Leather Belt", category: "belts", price: 119, images: ["/uploads/Belts.jpg"], size: ["S", "M", "L"], description: "Two-tone reversible belt with polished buckle.", colors: ["black", "brown"] },
  // { _id: "p-be-002", name: "Textured Buckle Belt", category: "belts", price: 109, images: ["/uploads/Belts.jpg"], size: ["M", "L"], description: "Subtle grain texture and brushed buckle.", colors: ["black"] },
  // { _id: "p-be-003", name: "Braided Suede Belt", category: "belts", price: 89, images: ["/uploads/Belts.jpg"], size: ["S", "M", "L"], description: "Braided suede for relaxed tailoring.", colors: ["tan"] },

  // Sunglasses
  // { _id: "p-sg-001", name: "Square Acetate Sunglasses", category: "sunglasses", price: 169, images: ["/uploads/sunglasses.jpg"], size: [], description: "Bold square frame with dark lenses.", colors: ["black"] },
  // { _id: "p-sg-002", name: "Thin Metal Round Sunglasses", category: "sunglasses", price: 149, images: ["/uploads/sunglasses.jpg"], size: [], description: "Lightweight round frame with refined bridge.", colors: ["gold"] },
  // { _id: "p-sg-003", name: "Gradient Lens Wayfarer", category: "sunglasses", price: 179, images: ["/uploads/sunglasses.jpg"], size: [], description: "Wayfarer frame with subtle gradient lenses.", colors: ["tortoise"] },

  // Lace-Ups
  // { _id: "p-lu-001", name: "Cap-Toe Derby", category: "lace-ups", price: 219, images: ["/uploads/Lace-Ups.jpg"], size: ["7", "8", "9", "10", "11"], description: "Cap-toe derby with a clean, formal stance.", colors: ["black"] },
  // { _id: "p-lu-002", name: "Wholecut Oxford", category: "lace-ups", price: 279, images: ["/uploads/Lace-Ups.jpg"], size: ["7", "8", "9", "10"], description: "Single-piece leather upper with minimal seams.", colors: ["black", "brown"] },
  // { _id: "p-lu-003", name: "Suede Chukka Lace-Up", category: "lace-ups", price: 199, images: ["/uploads/Lace-Ups.jpg"], size: ["8", "9", "10", "11"], description: "Soft suede with a refined casual silhouette.", colors: ["sand", "navy"] },

  // Loafers
  // { _id: "p-lo-001", name: "Penny Loafers", category: "loafers", price: 189, images: ["/uploads/Loafers.jpg"], size: ["7", "8", "9", "10", "11"], description: "Classic penny loafer with a sleek apron toe.", colors: ["black", "brown"] },
  // { _id: "p-lo-002", name: "Suede Tassel Loafers", category: "loafers", price: 209, images: ["/uploads/Loafers.jpg"], size: ["8", "9", "10"], description: "Tassel loafer in soft suede for evenings.", colors: ["navy", "tan"] },
  // { _id: "p-lo-003", name: "Bit Loafers", category: "loafers", price: 229, images: ["/uploads/Loafers.jpg"], size: ["7", "8", "9", "10"], description: "Metal bit detail with a formal finish.", colors: ["black"] },

  // Sneakers
  // { _id: "p-sn-001", name: "Minimal Leather Sneakers", category: "sneakers", price: 149, images: ["/uploads/Sneakers.jpg"], size: ["7", "8", "9", "10", "11"], description: "Minimal leather sneaker with tonal outsole.", colors: ["white", "black"] },
  // { _id: "p-sn-002", name: "Retro Runner Sneakers", category: "sneakers", price: 139, images: ["/uploads/Sneakers.jpg"], size: ["8", "9", "10", "11"], description: "Retro runner shape with modern comfort.", colors: ["gray", "navy"] },
  // { _id: "p-sn-003", name: "High-Top Canvas Sneakers", category: "sneakers", price: 119, images: ["/uploads/Sneakers.jpg"], size: ["7", "8", "9", "10"], description: "High-top canvas build with sturdy sole.", colors: ["black", "cream"] },

  // Denim
  {
    _id: "p-denim-001",
    name: "Classic Blue Denim Jeans (Pull & Bear)",
    category: "denim",
    price: 1155,
    images: ["/uploads/Classic Blue Denim Jeans (Pull & Bear).jpg"],
    size: ["30", "32", "34", "36", "38"],
    description: "Classic blue denim jeans in a relaxed straight fit.",
    colors: ["blue"],
  },
  {
    _id: "p-denim-002",
    name: "Dark Indigo Denim Jeans",
    category: "denim",
    price: 1155,
    images: ["/uploads/Dark Indigo Denim Jeans.jpg"],
    size: ["30", "32", "34", "36", "38"],
    description: "Dark indigo denim jeans with a clean tapered line.",
    colors: ["indigo"],
  },
  {
    _id: "p-denim-003",
    name: "Levi's Classic Blue Jeans",
    category: "denim",
    price: 1155,
    images: ["/uploads/Levi's Classic Blue Jeans.jpg"],
    size: ["30", "32", "34", "36", "38"],
    description: "Classic blue Levi's jeans for everyday wear.",
    colors: ["blue"],
  },
  {
    _id: "p-denim-004",
    name: "Light Wash Vintage Denim (Pull & Bear)",
    category: "denim",
    price: 1155,
    images: ["/uploads/Light Wash Vintage Denim (Pull & Bear).jpg"],
    size: ["30", "32", "34", "36", "38"],
    description: "Light wash vintage denim with a relaxed cropped fit.",
    colors: ["blue"],
  },
  {
    _id: "p-denim-005",
    name: "Medium Wash Levi's Cropped Jeans",
    category: "denim",
    price: 700,
    images: ["/uploads/Medium Wash Levi's Cropped Jeans.jpg"],
    size: ["30", "32", "34", "36", "38"],
    description: "Medium wash cropped Levi's jeans with a classic five-pocket shape.",
    colors: ["blue"],
  },

  // Korean Pants
  {
    _id: "p-korean-001",
    name: "Camo Wool Trousers (Gray)",
    category: "korean",
    price: 1200,
    images: ["/uploads/Camo Wool Trousers (Gray).jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Gray wool trousers with a cropped modern silhouette.",
    colors: ["gray"],
  },
  {
    _id: "p-korean-002",
    name: "Black Elastic-Waist Trousers",
    category: "korean",
    price: 1080,
    images: ["/uploads/Black Elastic-Waist Trousers.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Relaxed black trousers with an elasticated back waist.",
    colors: ["black"],
  },
  {
    _id: "p-korean-003",
    name: "Diesel Elastic-Back Chino (Cream)",
    category: "korean",
    price: 1100,
    images: ["/uploads/Diesel Elastic-Back Chino (Cream).jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Cream chino with a structured straight leg and elastic-back waist.",
    colors: ["cream"],
  },
  {
    _id: "p-korean-004",
    name: "Diesel Stretch Chino (Beige)",
    category: "korean",
    price: 1100,
    images: ["/uploads/Diesel Stretch Chino (Beige).jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Beige stretch chino with a tapered easy-wear fit.",
    colors: ["beige"],
  },

  // Jeans / Baggy Pants
  {
    _id: "p-baggy-001",
    name: "Black Tapered Cargo Pants",
    category: "jeans",
    price: 1200,
    images: ["/uploads/Black Tapered Cargo Pants.jpg"],
    size: ["M", "L", "XL", "2XL"],
    description: "Tapered black cargo pants with adjustable hems.",
    colors: ["black"],
  },
  {
    _id: "p-baggy-002",
    name: "Ribbed Cargo Knit Pant (Cream)",
    category: "jeans",
    price: 1200,
    images: ["/uploads/Ribbed Cargo Knit Pant (Cream).jpg"],
    size: ["M"],
    description: "Cream ribbed knit pants with oversized cargo pockets.",
    colors: ["cream"],
  },
  {
    _id: "p-baggy-003",
    name: "Medium Wash Cargo Denim Jeans",
    category: "jeans",
    price: 1155,
    images: ["/uploads/Medium Wash Cargo Denim Jeans.jpg"],
    size: ["30", "32", "34", "36", "38"],
    description: "Medium wash denim jeans with utility cargo paneling.",
    colors: ["blue"],
  },
];

const productsData = rawProductsData.map((product) => ({
  ...product,
  colors: resolveProductColors(product),
  images: product.images.map(withPublicAssetVersion),
  price: applyCatalogPriceOffset(product.price),
  discount: CATALOG_DISCOUNT,
}));

export default productsData;
